### ISSUE TITLE
ListVIew closing tag in separated XAML block

### ISSUE THREAD

**Issue by Prodigio** [dotnet/docs.de-de#105]
The closing tag of `ListView` is separated from the XAML block. Should be together.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3afc3f4f-bb7e-97fa-8ae2-31b5a550978b
* Version Independent ID: 279b1fbb-7225-1644-c6b1-12cdbbc05639
* Content: [Gewusst wie: Gruppieren von Elementen in einem ListView, in dem ein GridView implementiert ist](https://docs.microsoft.com/de-de/dotnet/framework/wpf/controls/how-to-group-items-in-a-listview-that-implements-a-gridview)
* Content Source: [docs/framework/wpf/controls/how-to-group-items-in-a-listview-that-implements-a-gridview.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/wpf/controls/how-to-group-items-in-a-listview-that-implements-a-gridview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #8369](https://github.com/dotnet/docs/issues/8369) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @Prodigio 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/8369

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
