### ISSUE TITLE
tour-of-csharp/statements - code samples not included completely

### ISSUE THREAD

**Issue by FlexOr2** [dotnet/docs.de-de#113]
The "code samples" in the statements section are not included completely anymore. 
Seems the cause are changes in the "Program.cs" file. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 017f9566-a4df-e294-d6e8-da9252469ca9
* Version Independent ID: 6665f9d5-24bf-ac0d-62f5-d63ed53132ed
* Content: [C#-Anweisungen – Überblick über C#](https://docs.microsoft.com/de-de/dotnet/csharp/tour-of-csharp/statements)
* Content Source: [docs/csharp/tour-of-csharp/statements.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/tour-of-csharp/statements.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello @FlexOr2 
Thank you for your feedback.
I'm checking the live page and I don't see any missing/broken code.
Can you please provide more information so we can work on this issue?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @FlexOr2 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/8935.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
