### ISSUE TITLE
No good example

### ISSUE THREAD

**Issue by GYOERFT** [dotnet/docs.de-de#126]
When overriding ToString at Derived the output would be the derived ToString. The example suggests "as" lets you act like handling the base class instead

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4bc2f58f-8fbc-9ff2-2312-8a5715536f1f
* Version Independent ID: 1dbd0d51-e1dc-8970-93f8-2a44fa71f7ba
* Content: [as – C#-Referenz](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/as)
* Content Source: [docs/csharp/language-reference/keywords/as.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/language-reference/keywords/as.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @GYOERFT 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/10578

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
