### ISSUE TITLE
BypassNGenAttribute needs AttributeTargetsAttribute

### ISSUE THREAD

**Issue by johannesvogel1** [dotnet/docs.de-de#148]
The Codesample for the BypassNGenAttribute is not valid, because the AttributeTarget is missing.

namespace System.Runtime
{
    **[AttributeUsage(AttributeTargets.Method)]**
    public class BypassNGenAttribute 
        : Attribute
    {
    }
}

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 085ecaf8-233f-82eb-c564-b05137c899b9
* Version Independent ID: e2088737-ec20-b083-0a26-c041003d12dd
* Content: [Ngen.exe (Native Image Generator)](https://docs.microsoft.com/de-de/dotnet/framework/tools/ngen-exe-native-image-generator#feedback)
* Content Source: [docs/framework/tools/ngen-exe-native-image-generator.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/tools/ngen-exe-native-image-generator.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @johannesvogel1
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13775](https://github.com/dotnet/docs/issues/13775) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @johannesvogel1

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/13775

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
