### ISSUE TITLE
Broken URL (404) for "Tiny YOLOv2 pre-trained model"

### ISSUE THREAD

**Issue by Countryen** [dotnet/docs.de-de#154]
Link to Pre-requisite "Tiny YOLOv2 pre-trained model" is not valid (404).
https://github.com/onnx/models/tree/master/tiny_yolov2

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Erkennen von Objekten mithilfe von Deep Learning mit ONNX und ML.NET - ML.NET](https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/object-detection-onnx#feedback)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs.de-de/blob/live/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by srvbpigh** [comment]
Hello, @Countryen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #15168](https://github.com/dotnet/docs/issues/15168) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Countryen

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/15168

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
