### ISSUE TITLE
Disable: Required assets to build and debug are missing from ....

### ISSUE THREAD

**Issue by ARambazamba** [dotnet/docs.de-de#161]
I have set ""csharp.suppressDotnetRestoreNotification": true," and still get this very annoying "Required assets ..." popup. As I am working in Monorepos most of the time, I would be grateful if you could give a hin on how to get rid of it.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Erste Schritte mit C# und Visual Studio Code - .NET Core](https://docs.microsoft.com/de-de/dotnet/core/tutorials/with-visual-studio-code#feedback)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @ARambazamba
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @ARambazamba, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/16399. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
