### ISSUE TITLE
The code can work well on .net fx 4.7 but not on dotnetcore3.1

### ISSUE THREAD

**Issue by jinsh2019** [dotnet/docs.de-de#175]
The code can work well on .net fx 4.7 but not on dotnetcore3.1
The error msg:
System.PlatformNotSupportedException:“Operation is not supported on this platform.”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c5f5f4b7-b600-d163-ccef-9cf4b0693419
* Version Independent ID: 6e986136-5b77-4abc-da4c-9366c10826d5
* Content: [如何：使用 CodeDOM 创建类](https://docs.microsoft.com/zh-cn/dotnet/framework/reflection-and-codedom/how-to-create-a-class-using-codedom#feedback)
* Content Source: [docs/framework/reflection-and-codedom/how-to-create-a-class-using-codedom.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/reflection-and-codedom/how-to-create-a-class-using-codedom.md)
* Product: **dotnet-framework**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @jinsh2019
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #17683](https://github.com/dotnet/docs/issues/17683) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @jinsh2019, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/17683. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
