### ISSUE TITLE
Kernel32.lib

### ISSUE THREAD

**Issue by Eduard-tmn** [dotnet/docs.de-de#177]
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7681eaa7-3e80-1d65-0654-f7ef627ac0b2
* Version Independent ID: e69dab7b-f5c5-0c95-8519-2cbef6bf3c47
* Content: [Идентификация функций в библиотеках DLL](https://docs.microsoft.com/ru-ru/dotnet/framework/interop/identifying-functions-in-dlls)
* Content Source: [docs/framework/interop/identifying-functions-in-dlls.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/interop/identifying-functions-in-dlls.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @Eduard-tmn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Eduard-tmn 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team
