### ISSUE TITLE
Add titel

### ISSUE THREAD

**Issue by 39r762193i** [dotnet/docs.de-de#199]
https://github.com/dotnet/docs.de-de/issues/198#issuecomment-640126125

**Comment by srvbpigh** [comment]
Hello, @39r762193i
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @39r762193i 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @39r762193i , 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @39r762193i 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
